apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    env: test
spec:
  containers:
  - name: redis
    image: redis:stable
  tolerations:
  - key: "pod"
    operator: "Exists"
    effect: "NoSchedule"

