apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx:stable
  tolerations:
  - key: "pod"
    operator: "Equal"
    value: "no"
    effect: "NoSchedule"

