---
apiVersion: v1
kind: Service
metadata:
  name: task-12
spec:
  selector:
    app: task-12
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-12
  labels:
    app: task-12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-12
  template:
    metadata:
      labels:
        app: task-12
    spec:
      containers:
      - name: task-12
        image: agw7uwh2tivf45vcjrb9vmoeog/task12-image
