---
apiVersion: v1
kind: Service
metadata:
  name: task-7-job
spec:
  selector:
    app: task-7-job
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: task-7-job
  labels:
    app: task-7-job
spec:
  containers:
    - name: task-7-job
      image: joji95/k8s-static-web-app
