---
apiVersion: v1
kind: Namespace
metadata:
  name: lab11-pod
  labels:
    name: lab11-pod
---
apiVersion: v1
kind: Pod
metadata:
  name: lab11-pod
spec:
  containers:
  - name: lab11-pod
    image: vish/stress
    resources:
      requests:
        memory: "100Mi"
        cpu: "100"
      limits:
        cpu: "100"
        memory: "200Mi"
    args: ["-cpus", "2"]
  restartPolicy: Never
