---
apiVersion: v1
kind: Namespace
metadata:
  name: task-15
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: task-15
  namespace: task-15
data:
  MY_HOST: "google.com"
---
apiVersion: v1
kind: Pod
metadata:
  name: task-15b
  namespace: task-15
spec:
  containers:
    - name: task-15b
      image: agw7uwh2tivf45vcjrb9vmoeog/task-15:latest
      command: ["bash", "-c"]
      args: ["export MY_HOST=$(cat /root/config/MY_HOST) && printenv | grep -i my_host && echo && /script/loop-script.sh"]
      volumeMounts:
        - name: config
          mountPath: "/root/config/"
          readOnly: true
  volumes:
  - name: config
    configMap:
      name: task-15
