version: "3.9"

volumes:
  redis:

services:
  redis:
    image: "redis:alpine"
    volumes:
      - .:/code
  web:
    build: .
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - FLASK_ENV=development
