---
apiVersion: v1
kind: Namespace
metadata:
  name: deploy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: deploy
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable
      serviceAccountName: gf
