---
apiVersion: v1
kind: Namespace
metadata:
  name: lab
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: lab
  name: gf
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: lab
  name: pod-interaction
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"] 
  verbs: ["create", "delete", "get", "list", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-interaction
  namespace: lab
subjects:
- kind: User
  name: gf
  namespace: lab
  apiGroup: 
roleRef:
  kind: Role
  name: pod-interaction
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: image-kubectl
  namespace: lab
spec:
  containers:
  - image: bitnami/kubectl
    name: image-kubectl
    command: ["/bin/sleep"]
    args: ["1d"]
  serviceAccountName: gf
  automountServiceAccountToken: false
