---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-job-server
  end:
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-job-server
            image: alpine
            command: ["/bin/sh"]
            args: 
            - -c
            - echo Hello from the cron-job-server, the time is $(date +%T).
          restartPolicy: Never
