---
apiVersion: v1
kind: Namespace
metadata:
  name: lab9-pod
  labels:
    name: lab9-pod
---
apiVersion: v1
kind: Pod
metadata:
  name: lab9-pod
spec:
  containers:
  - name: lab9-pod
    image: polinux/stress
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "100Mi"
    command: ["/usr/local/bin/stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1", "--verbose"]
  restartPolicy: Never
