---
apiVersion: v1
kind: Namespace
metadata:
  name: lab10-pod
  labels:
    name: lab10-pod
---
apiVersion: v1
kind: Pod
metadata:
  name: lab10-pod
spec:
  containers:
  - name: lab10-pod
    image: vish/stress
    resources:
      requests:
        memory: "100Mi"
        cpu: "0.5"
      limits:
        cpu: "1"
        memory: "200Mi"
        #command: ["/stress"]
    args: ["-cpus", "2"]
  restartPolicy: Never
