---
apiVersion: v1
kind: Namespace
metadata:
  name: task-16
---
apiVersion: v1
kind: Pod
metadata:
  name: task-16a
  namespace: task-16
spec:
  containers:
    - name: task-16a
      image: agw7uwh2tivf45vcjrb9vmoeog/task-15:latest
      env:
        - name: MY_HOST
          valueFrom:
            secretKeyRef:
              name: task-16
              key: MY_HOST
      command: ["bash", "-c"]
      args: ["export MY_HOST=$MY_HOST && printenv | grep -i my_host && echo && /script/loop-script.sh"]
